apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: postgres
  password: postgres
  database: ticketapp
---
apiVersion: v1
kind: Secret
metadata:
  name: supplier-secret
type: Opaque
stringData:
  connString: 'Server=postgres-clusterip:5432;User Id=postgres;Password=postgres;Database=ticketapp'

