apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.4-bookworm
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: database
        ports:
        - containerPort: 5432
        volumeMounts: 
        - mountPath: /var/data/postgres/data
          name: postgresdata
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
          - name: postgresdata
            persistentVolumeClaim:
              claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432